name: Clang Format

on:
  push:
    branches:
      - "main"

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Permission
        working-directory: .github/script
        run: chmod a+x clang-format.sh

      - name: Run clang-format.sh
        run: ./.github/script/clang-format.sh
