name: Generate Document

on:
  push:
    branches:
      - "main"

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Fetch more history to detect changes correctly
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.proto

      - name: Set up golang
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'

      - name: Add Permission
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: .github/script
        run: chmod a+x generate-document.sh

      - name: Run generate-document.sh
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ./.github/script/generate-document.sh
